// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh0InDwZW_mJ9du2UgSiibft7DI55Tk3w',
    appId: '1:875508944286:web:fdfd670547c6c81cd79a8f',
    messagingSenderId: '875508944286',
    projectId: 'my-companion-8163f',
    authDomain: 'my-companion-8163f.firebaseapp.com',
    storageBucket: 'my-companion-8163f.firebasestorage.app',
    measurementId: 'G-LWJT4K9NHR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0pk65hjn706XZNWzy3v_RVxXQGZ9DR9E',
    appId: '1:875508944286:android:c58e3fefc9c31149d79a8f',
    messagingSenderId: '875508944286',
    projectId: 'my-companion-8163f',
    storageBucket: 'my-companion-8163f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBulKrlihlhPhZX-lhbtemAhT7KWv8OxaQ',
    appId: '1:875508944286:ios:e1d2dfbe3ea1f59ad79a8f',
    messagingSenderId: '875508944286',
    projectId: 'my-companion-8163f',
    storageBucket: 'my-companion-8163f.firebasestorage.app',
    iosBundleId: 'com.example.myCompanion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBulKrlihlhPhZX-lhbtemAhT7KWv8OxaQ',
    appId: '1:875508944286:ios:e1d2dfbe3ea1f59ad79a8f',
    messagingSenderId: '875508944286',
    projectId: 'my-companion-8163f',
    storageBucket: 'my-companion-8163f.firebasestorage.app',
    iosBundleId: 'com.example.myCompanion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAh0InDwZW_mJ9du2UgSiibft7DI55Tk3w',
    appId: '1:875508944286:web:fa1f2713f387ca48d79a8f',
    messagingSenderId: '875508944286',
    projectId: 'my-companion-8163f',
    authDomain: 'my-companion-8163f.firebaseapp.com',
    storageBucket: 'my-companion-8163f.firebasestorage.app',
    measurementId: 'G-YGN0B9VLFB',
  );
}
